# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development: &development
  <<: *default
  database: <%= ENV.fetch("db_name") { "nmd_cms_dev" } %>
  username: <%= ENV.fetch("db_username") { "postgres" } %>
  password: <%= ENV.fetch("db_postgres") { "1" } %>
  host: <%= ENV.fetch("db_host") { "localhost" } %>
  port: <%= ENV.fetch("db_port") { "5432" } %>

staging:
  <<: *development

production:
  <<: *development
